default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: event_ms_development

test:
  <<: *default
  database: event_ms_test

production:
  <<: *default
  database: event_ms_production
  username: event_ms
  password: <%= ENV["EVENT_MS_DATABASE_PASSWORD"] %>
